### ISSUE TITLE
Incorrect behavior for DetectLabels method/docs in javascript SDK

### ISSUE THREAD

**Issue by nmwalsh** [awsdocs/amazon-rekognition-developer-guide#19]
## Problem
When using the javascript SDK, the `DetectLabels` method returns a valid 200 response code, but no labels or confidence values when using the code snippet below from the documentation (live: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Rekognition.html#detectLabels-property)

> Calling the detectLabels operation
```
var params = {
  Image: { /* required */
    Bytes: new Buffer('...') || 'STRING_VALUE' /* Strings will be Base-64 encoded on your behalf */,
    S3Object: {
      Bucket: 'STRING_VALUE',
      Name: 'STRING_VALUE',
      Version: 'STRING_VALUE'
    }
  },
  MaxLabels: 0,
  MinConfidence: 0.0
};
rekognition.detectLabels(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

## Resolution (Workaround)

While MaxLabels and MinConfidence being set to 0 should be as inclusive as possible (no limit to the number of response labels, with no minimum confidence required), a 200 response with no labels was returned until we removed them, at which point the same image would return valid labels and confidence values.

I'm not sure whether this is a mistake in the docs, the javascript SDK, or the backend service, just trying to pass along the bug and what made it occur. If there's somewhere else I should file a ticket for this, let me know.

**Comment by AWSChris** [comment]
I think that's an auto-generated example from the JavaScript SDK. I'll follow up with the SDK team about about either removing it (  the other example has a MaxLabels of 123 and should work) or updating it.

**Comment by nmwalsh** [comment]
Exactly -- when raising the MaxLabels/MinConfidence to large numbers (or removing them as I ended up doing), it worked as expected. Thanks for getting on this so quickly!

**Comment by AWSChris** [comment]
Example updated to a MaxLabels 0f 123 and Confidence of 70.
