### ISSUE TITLE
Face comparasion result

### ISSUE THREAD

**Issue by MohdAbid1092** [awsdocs/amazon-rekognition-developer-guide#30]
when i am comparing two images (source image is person id and target image is person image) in amazon console it gives 85% similarity score while the same images gives 16 % similarity programatically why this is happening i cant figure out 
please help me ............ its been 4 days i havnt found any solution

**Comment by AWSChris** [comment]
Hi, can I suggest posting your query on the Rekognition forum - https://forums.aws.amazon.com/forum.jspa?forumID=234. Members of the service team should be able to help you.
