### ISSUE TITLE
'faceId was not found in the collection.' occurs randomly in java using lambda

### ISSUE THREAD

**Issue by oscuroalma** [awsdocs/amazon-rekognition-developer-guide#31]
Flow of lambda
1) Indexing faces in collection abc
2) Searching faceid in same collection abc

works maximum times but sometimes gives error 'faceId was not found in the collection.' 
other than lambda if the same faceid is searched in same collection abc it gives correct output without any error

**Comment by AWSChris** [comment]
Hi, Apologies for the late response. I'm not sure what's causing your problem. Can I suggest posting your query to the Rekognition forum -https://forums.aws.amazon.com/forum.jspa?forumID=234. Members of the service team should be able to help.

**Comment by laviRZ** [comment]
@oscuroalma I'm encountering the same issue, did you manage to understand what's going on?
