### ISSUE TITLE
No mention of required headers for requests via REST

### ISSUE THREAD

**Issue by ymas086** [awsdocs/amazon-rekognition-developer-guide#33]
I tried to test the endpoints using Postman, just to ascertain that the keys I had generated had appropriate permissions for using rekognition services. Took me an incredibly long time to realize I had to pass a `x-amz-target` and a `content-type` header, because the documentation just does not mention them. At all.

Nowhere in your documentation can I find **COMPREHENSIVE** details on how to test rekognition (or any other amazon services) via REST, which is problematic for any frameworks or stacks that do not have active SDKs provided  out of the box.

**Comment by AWSChris** [comment]
Hi, I'll add a table of required headers for Rekognition within the next couple of days. I'll also see about adding an example. The general information for AWS services is here - https://docs.aws.amazon.com/general/latest/gr/aws-apis.html

**Comment by ymas086** [comment]
I found this information to be incredibly difficult to find. 

But thank you so much for the link. It was exactly what I was looking for.
