### ISSUE TITLE
Error AccessDenied 

### ISSUE THREAD

**Issue by IsabelChong** [awsdocs/amazon-rekognition-developer-guide#39]
Hello, I have been trying to create a stream processor using python on my Raspberry Pi. Below is the error I got:

`Traceback (most recent call last):
  File "/home/pi/Codes/AWS-Services/creating-stream-processor.py", line 34, in <module>
    main()
  File "/home/pi/Codes/AWS-Services/creating-stream-processor.py", line 32, in main
    create_stream_processor()
  File "/home/pi/Codes/AWS-Services/creating-stream-processor.py", line 26, in create_stream_processor
    'Arn': 'arn:aws:kinesis:ap-southeast-1:121234567890:stream/DataStream-bmebpd'
  File "/home/pi/.local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
**botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the CreateStreamProcessor operation: `**

Below is mycode for creating a stream processor for python:
'import boto3

def create_stream_processor():

    client = boto3.client('rekognition')
        
    response = client.create_stream_processor(
        Name='streamprocessor-bmebpd',
        RoleArn= 'arn:aws:iam::121234567890:role/Rekognition-bmebpd',
        Settings={
            'FaceSearch': {
                'FaceMatchThreshold': 80.0,
                'CollectionId': 'collection'
            }
        },
        Input={
            'KinesisVideoStream': {
                'Arn': 'arn:aws:kinesisvideo:ap-southeast-121234567890:stream/VideoStream/1234567890'
            }
        },
        Output={
            'KinesisDataStream': {
                'Arn': 'arn:aws:kinesis:us-east-1:121234567890:stream/DataStream'
            }
        }
    )

def main():
    create_stream_processor()
if __name__ == "__main__":
    main() '

I have given my roles FullAccess.

**Comment by dnelsamz** [comment]
Thank you for telling us about your issue. We'll look into this, diagnose the issue, and respond with an update as soon as possible.

**Comment by dnelsamz** [comment]
I've spent some time digging into the issue. Syntax for settings, input, and output look correct. If you have the access permissions set correctly for all services, check to ensure that you're both using the latest version of the SDK and that all the services you are using are located in the same region. As suggested by these [two ](https://github.com/aws/aws-cli/issues/4409) [similar ](https://github.com/awsdocs/amazon-rekognition-developer-guide/issues/18) errors, it looks like the API may occasionally return a `(AccessDeniedException)` error when there is a region-related compatibly issue. I hope this helps you.
