### ISSUE TITLE
infin loop 

### ISSUE THREAD

**Issue by Rayano2** [awsdocs/amazon-rekognition-developer-guide#4]
i used the same code but the result shown to infinite loop (.) waiting for result 

Waiting for job: c6798
false
....................
....................
....................
....................
....................
....................
....................
....................
....................

**Comment by AWSChris** [comment]
Most likely Rekognition doesn't have access to the SNS topic. Take a look at this topic - https://docs.aws.amazon.com/rekognition/latest/dg/api-video-roles.html.
Alternatively,  the SQS queue isn't subscribed to the SNS topic - https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-subscribe-queue-sns-topic.html
