### ISSUE TITLE
Load testing issue

### ISSUE THREAD

**Issue by ArulselvanJaya** [awsdocs/amazon-rekognition-developer-guide#45]
While doing load testing, we are getting below error.
    
**HTTP/1.0 500 Internal Server Error
Date: Mon, 12 Apr 2021 11:18:35 GMT
Server: Apache
X-XSS-Protection: 1; mode=block
X-FRAME-OPTIONS: SAMEORIGIN
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8**

We did 50 users, passed 42 users. Please help us to resolve the same. Testing and web server loads are normal.

**Comment by nijerica** [comment]
Hello,

Have you tried posting your question on the Amazon Rekognition forum? We recommend that you use that resource for the type of help you are looking for: http://forums.aws.amazon.com/forum.jspa?forumID=234.

You might also consider signing up for AWS technical support: https://aws.amazon.com/premiumsupport/.
