### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by cibinjohn** [awsdocs/amazon-rekognition-developer-guide#5]
I've used the same code. But Unfortunately, It is not working. What might be the possible reason?
(I have successfully implemented Objects_Labelling, Face_Detection, and Celebrity_Recognition on stored videos using aws rekognition. )

Following is the output. Any suggestions would be appreciated.

The result is,
Waiting for job: 9bf0dfe0912f48eb6621118c63b708bd2941edc9d01d4017587be1389b63193a
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
Job found was "9bf0dfe0912f48eb6621118c63b708bd2941edc9d01d4017587be1389b63193a"
Job id: "9bf0dfe0912f48eb6621118c63b708bd2941edc9d01d4017587be1389b63193a"
Status : "SUCCEEDED"
9bf0dfe0912f48eb6621118c63b708bd2941edc9d01d4017587be1389b63193a
Format: QuickTime / MOV
Codec: h264
Exception in thread "main" Duration: 26673
FrameRate: 16.496

Sec: 0Person number: 0
Matches in collection...
java.lang.NullPointerException
	at Facial_Rekognition.GetResultsFaceSearchCollection(Facial_Rekognition.java:267)
	at Facial_Rekognition.main(Facial_Rekognition.java:156)

**Comment by AWSChris** [comment]
I what's happening is that Rekognition doesn't return matched faces for each frame. I amended the example to deal with  cope accordingly. https://docs.aws.amazon.com/rekognition/latest/dg/procedure-person-search-videos.html
