### ISSUE TITLE
Rekognition Error Handling redirect to proper Service Limit page

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/amazon-rekognition-developer-guide#51]
On the amazon-rekognition-developer-guide error handling page:https://docs.aws.amazon.com/rekognition/latest/dg/error-handling.html,
the link under ProvisionedThroughputExceededException redirects to https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_rekognition which is just the generic AWS Service Quotas page.  Should that direct to https://docs.aws.amazon.com/general/latest/gr/rekognition.html or https://docs.aws.amazon.com/rekognition/latest/dg/limits.html?

**Comment by dnelsamz** [comment]
Thank you for identifying this issue with the link to the limits page! Your feedback helps us determine where to focus when improving our documentation.
