### ISSUE TITLE
Parameter validation failed:\nUnknown parameter in input: \"Features\"

### ISSUE THREAD

**Issue by thinki4** [awsdocs/amazon-rekognition-developer-guide#57]
Unable to get image properties using python 9

import json
import boto3
def lambda_handler(event, context):
    fileName='7up_Free.jpg'
    bucket='image-auditing-bucket'
    
    client=boto3.client('rekognition')

    #response = client.detect_labels(Image={'S3Object':{'Bucket':bucket,'Name':fileName}},MaxLabels=3,  MinConfidence=70,'Features':['GENERAL_LABELS'])
    
    response = client.detect_labels(
    Image={
        'S3Object': {
            'Bucket': bucket,
            'Name': fileName
        }
    },
    MaxLabels=123,
    MinConfidence=50,
    Features=[
        'GENERAL_LABELS','IMAGE_PROPERTIES',
    ],
    Settings={
        'ImageProperties': {
            'MaxDominantColors': 123
        }
    }
)

    print('Detected labels for ' + fileName)    
    for label in response['Labels']:
        print (label['Name'] + ' : ' + str(label['Confidence']))

Getting error

Test Event Name
test

Response
{
  "errorMessage": "Parameter validation failed:\nUnknown parameter in input: \"Features\", must be one of: Image, MaxLabels, MinConfidence\nUnknown parameter in input: \"Settings\", must be one of: Image, MaxLabels, MinConfidence",
  "errorType": "ParamValidationError",
  "requestId": "2f6b2ba3-79c3-4656-b2e8-0149955b9884",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 11, in lambda_handler\n    response = client.detect_labels(\n",
    "  File \"/var/runtime/botocore/client.py\", line 391, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/runtime/botocore/client.py\", line 691, in _make_api_call\n    request_dict = self._convert_to_request_dict(\n",
    "  File \"/var/runtime/botocore/client.py\", line 739, in _convert_to_request_dict\n    request_dict = self._serializer.serialize_to_request(\n",
    "  File \"/var/runtime/botocore/validate.py\", line 360, in serialize_to_request\n    raise ParamValidationError(report=report.generate_report())\n"
  ]
}

Function Logs
START RequestId: 2f6b2ba3-79c3-4656-b2e8-0149955b9884 Version: $LATEST
[ERROR] ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Features", must be one of: Image, MaxLabels, MinConfidence
Unknown parameter in input: "Settings", must be one of: Image, MaxLabels, MinConfidence
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 11, in lambda_handler
    response = client.detect_labels(
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 691, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/var/runtime/botocore/client.py", line 739, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/var/runtime/botocore/validate.py", line 360, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())END RequestId: 2f6b2ba3-79c3-4656-b2e8-0149955b9884
REPORT RequestId: 2f6b2ba3-79c3-4656-b2e8-0149955b9884	Duration: 867.77 ms	Billed Duration: 868 ms	Memory Size: 128 MB	Max Memory Used: 64 MB	Init Duration: 229.89 ms

Request ID
2f6b2ba3-79c3-4656-b2e8-0149955b9884

**Comment by dnelsamz** [comment]
Hello, my apologies for the late response. This isn't exactly an issue with the documentation, it seems like you're having an issue with the Boto3 SDK. From the error traceback it looks like Features isn't being recognized as a legitimate option. Please ensure you are using the most recent version of the SDK by updating it. If you continue to experience problems you can request more assistance by posting about your issue at the Repost forums -- https://repost.aws/ 

Thank you for taking the time to leave feedback on the documentation.
