### ISSUE TITLE
cannot start streamprocessor

### ISSUE THREAD

**Issue by dstsay** [awsdocs/amazon-rekognition-developer-guide#7]
Stream processor fails when trying to start with the AWS CLI.  I believe it has something to do with the role-arn because here is the output of when I invoke the describe-stream-processor command:

> aws rekognition describe-stream-processor --name facedetectstreamprocessor
1527352315.942	1527352346.269	mystreamprocessor	arn:aws:iam::123456789012:role/kinesisstreamrole	FAILED	Access denied to Role	arn:aws:rekognition:us-east-1:123456789012:streamprocessor/facedetectstreamprocessor
KINESISVIDEOSTREAM	arn:aws:kinesisvideo:us-east-1:123456789012:stream/videostreamtest
KINESISDATASTREAM	arn:aws:kinesis:us-east-1:123456789012:stream/facedetectstream
FACESEARCH	facestodetect	80.0

Invoking start_stream_processor has no errors, but when I look up status it says FAILED:

> aws rekognition start-stream-processor --name facedetectstreamprocessor
>
> aws rekognition list-stream-processors
STREAMPROCESSORS	facedetectstreamprocessor	FAILED

I am invoking these commands as the root user of my account.

Any help on this is appreciated - thanks!

**Comment by dstsay** [comment]
Nevermind - I figured out the role was not set with a trusted relationship to Rekognition

**Comment by ricardoreis** [comment]
@dstsay I have the same problem.
What did you do to fix it?
I create role whit "AmazonRekognitionServiceRole" policy.

**Comment by AWSChris** [comment]
@ricardoreis Is this still a problem for you? This topic should be able to help - https://docs.aws.amazon.com/rekognition/latest/dg/api-streaming-video-roles.html. Let me know if it doesn't.

**Comment by texano00** [comment]
Hi everyone,
i'm facing up on the same problem.
After i run
```  
rekognition.create_stream_processor(
        Input={
            'KinesisVideoStream': {
                'Arn': event['arnVideoStream']
            }
        },
        Output={
            'KinesisDataStream': {
                'Arn': event['arnDataStream']
            }
        },
        Name=event['processorName'],
        Settings={
            'FaceSearch': {
                'CollectionId': event['collectionId']
            }
        },
        RoleArn=event['roleArn']
)
    
rekognition.start_stream_processor(
      Name=event['processorName']
)
```
that stream is initially set to "STARTING", than "RUNNING"(for a second) and finally to "FAILED".

I've checked the arnRole and the kinesis role so they are right, can someone help me?
The streaming video is correctly running.

Thanks
